### PR TITLE
Rule check changes

### PR DESCRIPTION
**Pull request by NishithKashyap**

### CODE REVIEW

**Review by ashwin-borneo — COMMENTED** [review]
Could you also change the default sync to point to a new default_borneo_sync(). It should have only the AWS sync call and remove all the other Azure, GCP, etc calls. 

Also, test it completely on the local using temporal as well.

**Comment by NishithKashyap** [comment]
Have added the new borneo default sync, please let me know if there are any more stages that needs to be added

**Review by ashwin-borneo — APPROVED** [review]
Changes look good. Please test it locally before merge.

**Comment by NishithKashyap** [comment]
Changes working as expected, can I merge this change now? @ashwin-borneo

**Pull request merged**
